### ISSUE TITLE
"DataCloneError"

### ISSUE THREAD

**Issue by annevk** [dslomov/ecmascript-structured-clone#1]
Note that HTML uses DOMException whose name is "DataCloneError", not a DataCloneError object. You don't think we can change that?

**Comment by dslomov** [comment]
Rats. You are right. I do not know. Looks like quite a breaking change to me. Ideas?

**Comment by annevk** [comment]
Well, we have changed things like this in the past for DOM. It's usually fine, but we'd have to test. @arv can prolly help out.

**Comment by dslomov** [comment]
Hmm, I think we should not break the web just because we want to move a couple of specs around the standardization organizations ;)

Since the algorithm is not exposed to the language in any way, what do you think about one of:
- making error object an input to StructuredClone algo
- making %DataCloneError% a host-provided intrinsic in the realm

**Comment by annevk** [comment]
I suppose. The DOMException story is rather messy and not very stable, but either of those works for me too. The second one seems more stable long term. @allenwb, want to weigh in here?

**Comment by arv** [comment]
> The DOMException story is rather messy and not very stable

No two browsers agree on these and as long as we keep the `name` and possibly `code` properties stable I believe we can change a lot of things here.

**Comment by annevk** [comment]
Changing this would be too high risk.
